name: npm publish
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npm-publish
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org
      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn build
      - run: yarn npm publish
