name: npm publish
on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: zendesk/gw/.github/workflows/npm-publication.yml@main
    with:
      node_version: '22'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      NPM_TOTP_DEVICE: ${{ secrets.NPM_TOTP_DEVICE }}
